# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.19.3
loom_version=1.11.8

# Mod Properties
mod_version=1.3.1
maven_group=com.glamardor
archives_base_name=figura-performance

# Dependencies
fabric_api_version=0.136.1+1.21.8
modmenu_version=15.0.2
cloth_config_version=19.0.147
figura_jar=libs/figura-0.1.5+1.21.8-fabric-mc.jar
